duration param
ZK-solidity-army/farcaster_lottery pull request #14
Opened 2024-05-01 10:07 UTC by BanzaiTokyo

2024-05-01 11:24 UTC, gurobokum requested changes

2024-05-01 11:24 UTC, gurobokum commented on packages/hardhat/contracts/LotteryDeployer.sol
> +    require(duration <= 14 days);
Could you please provide error message

2024-05-01 11:24 UTC, gurobokum commented on packages/hardhat/contracts/LotteryDeployer.sol
> +    Lottery lottery = new Lottery(block.timestamp + duration);
I'm not sure but looks like by design would be better to calculate timestamp in Lottery itself

2024-05-01 11:24 UTC, gurobokum commented on packages/hardhat/contracts/LotteryDeployer.sol
>    function createLottery() external {
Needs a parama

2024-05-01 11:24 UTC, gurobokum commented on packages/hardhat/contracts/Lottery.sol
> +        _grantRole(DEVELOPER_ROLE, address(0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045));
I guess we need to pass this information from LotteryDeployer

2024-05-01 15:29 UTC, gurobokum requested changes

2024-05-01 15:29 UTC, gurobokum commented on packages/hardhat/contracts/Lottery.sol
> +        if (duration <= 0 || duration > 14 days) {
I think uint couldn't be negative

2024-05-01 15:29 UTC, gurobokum commented on packages/hardhat/contracts/Lottery.sol
> +        if (duration <= 0 || duration > 14 days) {
Also I prefer to send error message about duration longer than 14 days, it's more explicit

2024-05-01 15:30 UTC, gurobokum commented on packages/hardhat/contracts/Lottery.sol
> +        if (duration <= 0 || duration > 14 days) {
Could you please also fix lint error

2024-05-02 09:55 UTC, gurobokum commented on packages/nextjs/app/frames/lottery/route.tsx
> +        <Image
It should be img for frame, also it's warning not error

2024-05-02 09:56 UTC, gurobokum requested changes
Linter still fails

2024-05-02 10:09 UTC, BanzaiTokyo commented on packages/nextjs/app/frames/lottery/route.tsx
> +        <Image
reverted. But it kinda looks like an error
![Screenshot 2024-05-02 at 12 09 01](https://github.com/ZK-solidity-army/farcaster_lottery/assets/2467506/e7c0f743-86d3-4980-a6a6-4de559bba19f)

2024-05-02 13:35 UTC, gurobokum commented on packages/hardhat/contracts/Lottery.sol
> +            starterFee = _starterFee;
```suggestion
       starterFee = _starterFee;
```

2024-05-07 18:52 UTC, gurobokum approved these changes

2024-05-07 19:08 UTC, merged